### PR TITLE
fix(hydration): generate cache with search parameters from server-side request

### LINKED ISSUE #5964: deserializeQueryParameters - TypeError: Cannot read properties of undefined (reading 'split')
## Unhandled Runtime Error

image

## Here is the line of the error code 👇

image

## Localhost console debug

Did a quick debug and found that the `result` item from `deserializeQueryParameters` has no `params` key. 

image

### 🔍 Steps to reproduce

I have updated the libraries and this error appeared

algoliasearch: 4.20.0 > 4.21.1 
instantsearch.js: 4.58.0 > 4.62.0
react-instantsearch: 7.2.0 > 7.4.1
react-instantsearch-core: 7.2.0 > 7.4.1
react-instantsearch-router-nextjs: 7.2.0 > 7.4.1

### Live reproduction

-

### 💭 Expected behavior

Working code

### Package version

react-instantsearch: 7.4.1, react-instantsearch-core: 7.4.1, react-instantsearch-router-nextjs: 7.4.1, instantsearch.js: 4.62.0, algoliasearch: 4.21.1

### Operating system

_No response_

### Browser

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dhayab**
**Summary**

In an SSR context, the search request performed server-side is cached in the client-side search client to prevent sending an unnecessary duplicate request when the user interacts with refinements.

This is done by manually recomposing the cached results during hydration and adding it to the search client's cache mechanism. The key of a cached request uses the search parameters from the response, normally returned by Algolia, but customers can limit what fields are returned by setting the `responseFIelds` option. If `params` is omitted, than the app throws an error during hydration.

This PR changes slightly how the request key is crafted, by instead extracting the request search parameters from the server-side search request, and using it instead of the response search parameters.

**Result**

Hydration now works correctly and the server-side request is effectively cached whether fields are filtered using `responseFields` or not.

> [!NOTE]
> The issue of cache miss in implementations containing multiple indices is still unsolved and can be handled by FX-2720.
> Furthermore, if in those multiple indices there are multiples of the same `indexName` + `indexId`, the current implementation of `getInitialResults()` uses only the last instance for params and results, which might not be desirable.

Fixes #5964 
FX-2702

### CODE REVIEW

File: packages/instantsearch.js/src/lib/server.ts [hunk 1]
```diff
@@ -37,17 +55,28 @@ export function waitForResults(search: InstantSearch): Promise<void> {
...
     if (searchResults) {
-      initialResults[widget.getIndexId()] = {
+      const indexId = widget.getIndexId();
+      initialResults[indexId] = {
         // We convert the Helper state to a plain object to pass parsable data
         // structures from server to client.
         state: { ...searchResults._state },
         results: searchResults._rawResults,
+        requestParams: requestParams?.find(
+          ({ indexName }) => indexName === indexId
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/server.ts:78]: this should use the widget's index name, not index id

Comment (dhayab) [reply packages/instantsearch.js/src/lib/server.ts:78]: Ah I see. I'll update the sample code to use multiple of the same index with different ids and check if I can match request + results in the hydration step.

Comment (dhayab) [reply packages/instantsearch.js/src/lib/server.ts]: I simplified the implementation as extracted request params and initial results are ordered identically.

File: packages/instantsearch.js/src/lib/server.ts [hunk 2]
```diff
@@ -37,17 +57,27 @@ export function waitForResults(search: InstantSearch): Promise<void> {
...
     if (searchResults) {
-      initialResults[widget.getIndexId()] = {
+      const indexId = widget.getIndexId();
+      const requestParams = requestParamsList?.shift();
+      initialResults[indexId] = {
         // We convert the Helper state to a plain object to pass parsable data
         // structures from server to client.
         state: { ...searchResults._state },
         results: searchResults._rawResults,
+        ...(requestParams && { requestParams }),
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/server.ts:80]:
```suggestion
       requestParams,
```

What's the difference with this? undefined if it's not available?

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx [hunk 3]
```diff
@@ -26,7 +38,7 @@ export function InitializePromise() {
 
   const injectInitialResults = () => {
     let inserted = false;
-    const results = getInitialResults(search.mainIndex);
+    const results = getInitialResults(search.mainIndex, requestParamsList);
```
Comment (Haroenv) [inline packages/react-instantsearch-nextjs/src/InitializePromise.tsx:41]: I guess I don't really understand this code right now, but how come this can't be read from waitForResults? does it need to be set before the results are known or something?

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx [hunk 4]
```diff
@@ -17,6 +19,16 @@ export function InitializePromise() {
       throw new Error('Missing ServerInsertedHTMLContext');
     });
 
+  // Extract search parameters from the search client to use them
+  // later during hydration.
+  let requestParamsList: Array<SearchOptions | undefined>;
```
Comment (Haroenv) [inline packages/react-instantsearch-nextjs/src/InitializePromise.tsx:24]: params is always defined, no? why isn't this:

```suggestion
  let requestParamsList: SearchOptions[];
```

File: packages/instantsearch.js/src/lib/server.ts [hunk 5]
```diff
@@ -37,17 +57,27 @@ export function waitForResults(search: InstantSearch): Promise<void> {
...
+   * returned by `waitForResults()`.
+   */
+  requestParamsList?: RequestParams[]
+): InitialResults {
   const initialResults: InitialResults = {};
 
   walkIndex(rootIndex, (widget) => {
     const searchResults = widget.getResults();
     if (searchResults) {
-      initialResults[widget.getIndexId()] = {
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/server.ts:46]: I'm fine with keeping the indexId variable, but just making sure that it's not doing anything now

File: packages/instantsearch.js/src/lib/server.ts [hunk 6]
```diff
@@ -37,17 +57,27 @@ export function waitForResults(search: InstantSearch): Promise<void> {
...
+      const indexId = widget.getIndexId();
+      const requestParams = requestParamsList?.shift();
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/server.ts:74]: should we keep track of the index and use the item at index `i` instead of mutating? Not sure if it's a good idea that `getInitialResults` effectively can only be called once (also let's add a test for calling it multiple times)

File: packages/instantsearch.js/src/lib/server.ts [hunk 7]
```diff
@@ -37,17 +57,27 @@ export function waitForResults(search: InstantSearch): Promise<void> {
 /**
  * Walks the InstantSearch root index to construct the initial results.
  */
-export function getInitialResults(rootIndex: IndexWidget): InitialResults {
+export function getInitialResults(
+  rootIndex: IndexWidget,
+  /**
+   * Search parameters sent to the search client, usually
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/server.ts:63]: usually?

File: packages/instantsearch.js/src/lib/server.ts [hunk 8]
```diff
@@ -1,21 +1,41 @@
...
 
-import type { IndexWidget, InitialResults, InstantSearch } from '../types';
+import type {
+  IndexWidget,
+  InitialResults,
+  InstantSearch,
+  SearchOptions,
+} from '../types';
+
+type RequestParams = SearchOptions | undefined;
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/server.ts:10]: same question, how can this be undefined?

File: packages/instantsearch.js/src/lib/__tests__/server.test.ts [hunk 9]
```diff
@@ -239,4 +249,52 @@ describe('getInitialResults', () => {
       },
     });
   });
+
+  test('returns the current results with request params if specified', async () => {
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/__tests__/server.test.ts:253]: we need another test with two indices with the same indexName and indexId that aren't adjacent too I think. I wonder if the deduplication could cause issues

File: packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts [hunk 10]
```diff
@@ -34,16 +34,24 @@ export function hydrateSearchClient(
     return;
   }
 
-  const cachedRequest = Object.keys(results).map((key) =>
-    results[key].results.map((result) => ({
-      indexName: result.index,
+  const cachedRequest = Object.keys(results).map((key) => {
+    const { state, requestParams, results: serverResults } = results[key];
+    return serverResults.map((result) => ({
+      indexName: result.index || state.index,
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts:40]:
```suggestion
      indexName: state.index || result.index,
```

Comment (Haroenv) [reply packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts:40]: this should be good if we ever add a feature in the backend that redirects indices (I believe I've heard of it, not sure if it ever came to fruition)

File: packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts [hunk 11]
```diff
@@ -34,16 +34,24 @@ export function hydrateSearchClient(
...
       // We normalize the params received from the server as they can
       // be serialized differently depending on the engine.
-      params: serializeQueryParameters(
-        deserializeQueryParameters(result.params)
-      ),
-    }))
-  );
+      // We use search parameters from the server request to craft the cache
+      // if possible, and fallback to those from results if not.
+      ...(requestParams || result.params
```
Comment (Haroenv) [inline packages/instantsearch.js/src/lib/utils/hydrateSearchClient.ts:45]: can we early return if `!(requestParams || result.params)` so we don't need the conditional in this map?

**Review by Haroenv — COMMENTED** [review]
Thanks for tackling this! I think it can do with a couple more tests of more advanced features though

File: packages/instantsearch.js/src/lib/server.ts (hunk 2 above)
Comment (dhayab) [reply packages/instantsearch.js/src/lib/server.ts:80]: Yes, if it's `undefined` it will throw because Next won't serialize it as JSON.

The 2 options are either omitting the property or returning `null`. I chose the first option in this case.

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx (hunk 3 above)
Comment (dhayab) [reply packages/react-instantsearch-nextjs/src/InitializePromise.tsx:41]: It's similar to what's in server.ts for the pages router, just that because we have access to the search instance outside of both `waitForResults()` and `injectInitialResults()`, it allows me to put the code that extracts the queries params before and directly reference them instead of passing them as a return value of promises.

File: packages/instantsearch.js/src/lib/server.ts (hunk 5 above)
Comment (dhayab) [reply packages/instantsearch.js/src/lib/server.ts:46]: I can revert that you're right.

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx (hunk 4 above)
Comment (dhayab) [reply packages/react-instantsearch-nextjs/src/InitializePromise.tsx:24]: `params` is typed as an optional parameter

File: packages/instantsearch.js/src/lib/server.ts (hunk 7 above)
Comment (dhayab) [reply packages/instantsearch.js/src/lib/server.ts:63]: There's a follow-up below 😅

> Search parameters sent to the search client, usually returned by `waitForResults()`.

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx (hunk 3 above)
Comment (Haroenv) [reply packages/react-instantsearch-nextjs/src/InitializePromise.tsx:41]: my question was more about the potential desynchronising of the search client wrapper in the future if we do any changes to that. Not sure if it matters

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx (hunk 4 above)
Comment (Haroenv) [reply packages/react-instantsearch-nextjs/src/InitializePromise.tsx:24]: right, but when is it actually undefined? isn't it always there? is that to avoid a BC on internal API?

File: packages/instantsearch.js/src/lib/server.ts (hunk 7 above)
Comment (Haroenv) [reply packages/instantsearch.js/src/lib/server.ts:63]: I mean when is it not returned from waitForResults?

Comment (dhayab) [reply packages/instantsearch.js/src/lib/server.ts:63]: Ah I get it, currently, never. I'll remove this word.

File: packages/instantsearch.js/src/lib/__tests__/server.test.ts (hunk 9 above)
Comment (Haroenv) [reply packages/instantsearch.js/src/lib/__tests__/server.test.ts:253]: if you walk through the indices, you should be able to "skip back" to a previous result if you store the "request ids" in order right?


pseudo code for how that could work in the hydration of index widgets phase:

```js
let currentIndex = 0
let seenIndexIds: Record<IndexId, number> = {};
walkIndex(({indexName, indexId}) => {
  currentIndex = seenIndexIds[indexId] ?? currentIndex + 1;
  seenIndexIds[indexId] = currentIndex
})
```

Comment (dhayab) [reply packages/instantsearch.js/src/lib/__tests__/server.test.ts:253]: I looked at it and it's actually working as expected: there are as many `requestParams` as there are `walkIndex()` iterations.

The reason there's a mismatch later on is actually unrelated, `initialResults` is an object that is keyed by index ids, so the same index ids in later iterations overwrite previous ones.

I don't know if we should be more restrictive about having multiple identical index ids, but at least I can it knowingly and comment on the context.

Comment (Haroenv) [reply packages/instantsearch.js/src/lib/__tests__/server.test.ts:253]: Hmm that makes sense. I guess we can separately make sure initialResults contains the combined results / uiState, and not accidentally only those of one instance

File: packages/react-instantsearch-nextjs/src/InitializePromise.tsx (hunk 4 above)
Comment (dhayab) [reply packages/react-instantsearch-nextjs/src/InitializePromise.tsx:24]: This type is optional because you could send manual requests with the client, where queries don't require `params` to be set (https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/#method-param-query-object).

In practice with InstantSearch, the helper always build the requests queries with params.

Comment (Haroenv) [reply packages/react-instantsearch-nextjs/src/InitializePromise.tsx]: Fine to be extra wary I guess :)

**Review by Haroenv — APPROVED** [review]
I think this is good to go, however, in the future we need a good look at FX-2720 in detail (and probably also in the scope of FX-2713, maybe even warn or error for that use case as it may be broken)

Not fully sure if the code duplication around param extraction between React InstantSearch and InstantSearch.js is good long-term but ok I think
