### PR TITLE
fix(DynamicWidgets): prevent non-stable fallbackComponent

### LINKED ISSUE #5530: createInstantSearchRouterNext without SSR clears state when filters are applied
### 🐛 Current behavior

Clicking refinements briefly shows the filtered items, and then reverts the selection when using createInstantSearchRouterNext in client-side only mode.

### 🔍 Steps to reproduce

1. Clone https://github.com/jmotes-lapero/algolia-issues-repro
2. `npm install`
3. `npm run dev`
4. Try to apply facet filters

### Live reproduction

https://codesandbox.io/s/github/jmotes-lapero/algolia-issues-repro

### 💭 Expected behavior

Checkboxes should persist and search results filtered by the new facet value.

### Package version

react-instantsearch-hooks-router-nextjs 6.40.1

### Operating system

Ubuntu Linux

### Browser

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Haroenv**
All our documentation makes sure to use stable references, although it could also make sure to clarify that is a requirement as well.

**Summary**

When you re-render and use a fallbackComponent which isn't stable, this causes that widget to unmount and remount (as a different widget). We now prevent that by making sure (and warning when it isn't) that fallbackComponent is stable.

Note that this could be considered breaking if someone was _only_ rendering when the widget actually changed (some other state possibly), but I'd consider that code already broken personally, as a render happening when the widget doesn't change would erase the state.

fixes #5530

**Result**

- add a warning when the fallbackComponent isn't stable
- only ever use the first value of fallbackComponent

### CODE REVIEW

**Review by aymeric-giraudet — APPROVED** [review]

File: packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx [hunk 1]
```diff
@@ -26,9 +27,16 @@ export type DynamicWidgetsProps = Omit<
...
-  fallbackComponent: Fallback = FallbackComponent,
+  fallbackComponent: Fallback = DefaultFallbackComponent,
   ...props
 }: DynamicWidgetsProps) {
+  const FallbackComponent = React.useRef(Fallback);
+
+  warn(
+    Fallback === FallbackComponent.current,
+    'The `fallbackComponent` prop of `DynamicWidgets` changed between renders. Please provide a stable reference.'
+  );
```
Comment (dhayab) [inline packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx:38]: Would adding a link to the doc and update it to show an example of how to achieve that help?

I'm thinking of this part: https://www.algolia.com/doc/api-reference/widgets/dynamic-facets/react-hooks/#widget-param-fallbackcomponent.

Comment (Haroenv) [reply packages/react-instantsearch-hooks/src/components/DynamicWidgets.tsx:38]: is 0f6c9fe clear?

**Review by dhayab — APPROVED** [review]
