### PR TITLE
fix(insights): deduplicate view events

### LINKED ISSUE #5442: Insight track function called multiple times
### Insights track called multiple times

Insights track function is called as many times as the useHits hook or Hit component are used in the InstantSearch component.

### 🔍 Steps to reproduce

Go to the live reproduction
See the multiple logs in the console
Remove one component using the useHits hook
See the number of logs decreasing

### Live reproduction

https://codesandbox.io/s/relaxed-james-x92y0k?file=/src/App.tsx

### 💭 Expected behavior

the 'view Hits' event is supposed to be called juste one time, regardless of how many times you used the useHits hook.

### Package version

algoliasearch 4.14.3, instantsearch.js 4.43.1, react-instantsearch-hooks-web 6.38.1, search-insights 2.2.3-hooks-web

### Operating system

_No response_

### Browser

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aymeric-giraudet**
**Summary**

[CR-6960](https://algolia.atlassian.net/browse/CR-6960)

Fixes #5442

**Result**

Only did it for view events because they're the only ones that we got issues for.
Tried to make it a bit more future proof for when we implement it with intersection observer, we look for differences between what we try to send vs what was already sent.
It resets when we receive a new query.

[CR-6960]: https://algolia.atlassian.net/browse/CR-6960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts [hunk 1]
```diff
@@ -438,13 +438,39 @@ export function createInsightsMiddleware<
           };
         }
 
+        const viewedObjectIDs = new Set<string>();
+        let lastQueryId: string | undefined;
+        instantSearchInstance.mainHelper!.derivedHelpers[0].on(
+          'result',
+          ({ results }) => {
+            if (!results.queryID || results.queryID !== lastQueryId) {
+              lastQueryId = results.queryID;
```
Comment (Haroenv) [inline packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts:447]: I guess this works with multi-index too as if one index changes, they all change?

**Review by Haroenv — APPROVED** [review]

File: packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts (hunk 1 above)
Comment (aymeric-giraudet) [reply packages/instantsearch.js/src/middlewares/createInsightsMiddleware.ts:447]: Yes :)
